openapi: 3.0.3
info:
  description: "API for Example Inditex"
  version: "0.0.1"
  title: "BcncInditex"
  contact:
    name: "Miguel Arredondo Calderon"
    email: "miguel.arredondo.calderon@gmail.com"
servers:
  - url: /v1
paths:
  /prices:
    get:
      summary: Obtener precio aplicable
      tags:
        - Prices
      description: Devuelve el precio final aplicar de un producto para fecha específica.
      parameters:
        - name: applicationDate
          in: query
          description: Fecha de aplicación en formato YYYY-MM-DD.
          required: true
          schema:
            type: string
            pattern: '^\d{4}-\d{2}-\d{2}$'
        - name: productId
          in: query
          description: Identificador del producto.
          required: true
          schema:
            type: integer
        - name: brandId
          in: query
          description: Identificador de la cadena.
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Obtención de precios encontrados
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/price"
        '404':
          description: Precio no encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Precio no encontrado
        '400':
          description: Parámetros de entrada inválidos
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Parámetros de entrada inválidos
components:
  schemas:
    price:
      type: object
      required:
        - productId
        - brandId
        - tariff
        - applicationStartDate
        - applicationEndDate
        - finalPrice
      properties:


        brandId:
          type: integer
          description: "Identificador de la cadena"
        tarifApli:
          type: integer
          description: "Tarifa a aplicar"
        applicationStartDate:
          type: string
          description: "Fecha de inicio de la aplicación de la tarifa (YYYY-MM-DD)"
        applicationEndDate:
          type: string
          description: "Fecha de fin de la aplicación de la tarifa (YYYY-MM-DD)"
        finalPrice:
          type: number
          format: float
          description: "Precio final a aplicar"
        money:
          type: string
          description: "Tipo de moneda"
      additionalProperties: false
tags:
  - name: Prices
    description: Obtener los precios resultado
