
server:
  port: 8081

spring:
  application:
    name: inditex

  datasource:
    url: jdbc:h2:mem:bcnc
    username: sa
    password:
    driverClassName: org.h2.Driver
    data: classpath:data.sql
    schema: classpath:schema.sql
    sql-script-encoding: UTF-8

  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update  # create-drop (es bueno si en elos test no indicas create table if not exits), validate (no arranca si no lo valida)
      use_sql_comments: true
      format_sql: true

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false


#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.type.descriptor.sql.BasicBinder: trace
